### ISSUE TITLE
Use name + profile pic along with twitter handle

### ISSUE THREAD

**Issue by punchagan** [baali/SoFee#5]
Often, people change their twitter handles, etc. It makes more sense to show name + profile pic along with the twitter handle.

**Comment by baali** [comment]
I tried looking for API from twitter which can give me twitter profile but didn't find any. If and when implemented It would need to be stored in models, profile_pic url, screen_name(handle), and name.

**Comment by baali** [comment]
This one is fixed, now we are storing extra information in json field.
